src/MVCProject.Web/Areas/Admin/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;
using MigraineDiary.Web.Controllers;
using System.Security.Claims;

namespace MigraineDiary.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IArticleService articleService;

        public ArticleController(IArticleService articleService)
        {
            this.articleService = articleService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            ArticleAddFormModel model = new ArticleAddFormModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ArticleAddFormModel addModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addModel);
            }

            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await articleService.CreateArticle(addModel, currentUserId);

            // Get controller's name and action's name without using magic strings.
            string actionName = nameof(HomeController.Index);
            string controllerName = nameof(HomeController).Substring(0, nameof(HomeController).Length - "Controller".Length);

            return RedirectToAction(actionName, controllerName, new { area = "" });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string articleId)
        {
            // Return bad request if hidden input field with correct articleId is deleted from HTML form.
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                // Get article which is going to be edited.
                ArticleEditModel article = await this.articleService.GetByIdAsync(articleId);

                return View(article);
            }
            catch (ArgumentException ae)
            {
                // TODO: Log exception.

                // Return bad request if parameter tampering is detected.
                return BadRequest();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ArticleEditModel editedArticle)
        {
            if (!ModelState.IsValid)
            {
                return View(editedArticle);
            }

            try
            {
                // Edit existing article.
                await this.articleService.EditAsync(editedArticle);

                // Get controller name and action name without using magic strings
                string actionName = nameof(HomeController.Index);
                string controllerName = nameof(HomeController).Substring(0, nameof(HomeController).Length - "Controller".Length);

                return RedirectToAction(actionName, controllerName, new { area = "area" });
            }
            catch (ArgumentException ae)
            {
                // TODO: Log exception.

                // Return bad request if parameter tampering is detected and article with sent Id does not exist.
                return BadRequest();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Archive(string articleId)
        {
            // Return bad request if hidden input field with correct articleId is deleted from HTML form.
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                // Mark article as deleted.
                await this.articleService.SoftDeleteAsync(articleId);

                // Get controller name and action name without using magic strings
                string actionName = nameof(HomeController.Index);
                string controllerName = nameof(HomeController).Substring(0, nameof(HomeController).Length - "Controller".Length);

                return RedirectToAction(actionName, controllerName, new { area = "area" });
            }
            catch (ArgumentException ae)
            {
                // TODO: Log exception.

                // Return bad request if parameter tampering is detected and article with sent Id does not exist.
                return BadRequest();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string articleId)
        {
            // Return bad request if hidden input field with correct articleId is deleted from HTML form.
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                // Delete article
                await this.articleService.DeleteAsync(articleId);

                // Get controller name and action name without using magic strings
                string actionName = nameof(HomeController.Index);
                string controllerName = nameof(HomeController).Substring(0, nameof(HomeController).Length - "Controller".Length);

                return RedirectToAction(actionName, controllerName, new { area = "area" });
            }
            catch (ArgumentException ae)
            {
                // TODO: Log exception.

                // Return bad request if parameter tampering is detected and article with sent Id does not exist.
                return BadRequest();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UndoDelete(string articleId)
        {
            // Return bad request if hidden input field with correct articleId is deleted from HTML form.
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                // Undo soft delete.
                await this.articleService.UndoDeleteAsync(articleId);

                // Get controller name and action name without using magic strings
                string actionName = nameof(ArticleController.Archived);
                string controllerName = nameof(ArticleController).Substring(0, nameof(ArticleController).Length - "Controller".Length);

                return RedirectToAction(actionName, controllerName/*, new { area = "area" }*/);
            }
            catch (ArgumentException ae)
            {
                // TODO: Log exception.

                // Return bad request if parameter tampering is detected and article with sent Id does not exist.
                return BadRequest();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Archived(int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            PaginatedList<ArticleViewModel> articles = await this.articleService.GetArchivedArticles(pageIndex, pageSize, orderByDate);

            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;
            return View(articles);
        }
    }
}

src/MVCProject.Web/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;
using System.Security.Claims;

namespace MigraineDiary.Web.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IArticleService articleService;

        public ArticleController(IArticleService articleService)
        {
            this.articleService = articleService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            ArticleAddFormModel model = new ArticleAddFormModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ArticleAddFormModel addModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addModel);
            }

            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            await this.articleService.CreateArticle(addModel, currentUserId);

            // Get controller's name and action's name without using magic strings.
            string actionName = nameof(HomeController.Index);
            string controllerName = nameof(HomeController).Substring(0, nameof(HomeController).Length - "Controller".Length);

            return RedirectToAction(actionName, controllerName);
        }
    }
}

src/MVCProject.Web/Areas/Admin/Views/Article/Add.cshtml
@model ArticleAddFormModel

@{
    ViewData["Title"] = "Add article";
}

<link href="~/css/froala/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />

<header>
    <h3 class="text-center mb-3">Добави публикация</h3>
</header>
<main>
    <div class="add-article-container">
        <form asp-area="Admin" asp-controller="Article" asp-action="Add" method="post" class="add-article-flex-item text-center">
            <div>
                <label asp-for="@Model.Title" class="mt-3">Заглавие</label>
                <input type="text" asp-for="@Model.Title" class="form-control" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>
           
            <div>
                <label asp-for="@Model.Content" class="mt-3">Съдържание</label>
                <textarea id="content" name="content"></textarea>
                <span asp-validation-for="@Model.Content" class="text-danger"></span>
            </div>
            
            <div>
                <label asp-for="@Model.Author" class="mt-3">Автор(и)</label>
                <input type="text" asp-for="@Model.Author" class="form-control" />
                <span asp-validation-for="@Model.Author" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="@Model.SourceUrl" class="mt-3">URL на източник</label>
                <input type="text" asp-for="@Model.SourceUrl" class="form-control" />
                <span asp-validation-for="@Model.SourceUrl" class="text-danger"></span>
            </div>

            <input type="submit" value="Публикувай" class="btn btn-primary mt-3" />
        </form>
    </div>
</main>

<script type="text/javascript" src="~/js/froala/froala_editor.pkgd.min.js"></script>
<script type="text/javascript" src="~/js/InitializeFroala.js"></script>

src/MVCProject.Web/Areas/Admin/Views/Article/Archived.cshtml
@model PaginatedList<ArticleViewModel>

@{
    ViewData["Title"] = "Архивирани публикации";
    ViewData["PartialViewController"] = "Home";
    ViewData["PartialViewAction"] = "Index";
    ViewData["itemsType"] = "Публикации";
}

<link href="~/css/froala/froala_style.min.css" rel="stylesheet" type="text/css" />

@if (Model.Count == 0)
{
    <p class="text-center article-title mt-0">Не са открити архивирани публикации.</p>
}
else
{
    <main>
        <h3 class="text-center">Архивирани публикации</h3>
        <partial name="_PageItemsOrderingNavigation" view-data="ViewData">
            <section>
                @foreach (var article in Model)
                {
                    <article class="article-container">
                        <h5 class="article-title">@article.Title</h5>
                        <div class="article-info">
                            <div>Автори: @article.Author</div>
                            <div>Публикувано: @article.CreatedOn.ToShortDateString()</div>
                        </div>
                        <div class="fr-view article-content">
                            @Html.Raw(article.Content)
                        </div>
                        @if (article.SourceUrl != null)
                        {
                            <div class="text-center mt-3">
                                <span>Източник: @article.SourceUrl</span>
                            </div>
                        }
                        <div class="article-admin-area-container">
                            <form asp-area="Admin" asp-controller="Article" asp-action="UndoDelete" method="post">
                                <input type="hidden" name="articleId" value="@article.Id" />
                                <button type="submit" class="btn btn-success border-dark" title="Прави публикацията отново видима за потребителите.">Възстанови</button>
                            </form>
                            <form asp-area="Admin" asp-controller="Article" asp-action="Delete" method="post">
                                <input type="hidden" name="articleId" value="@article.Id" />
                                <button type="submit" class="btn btn-danger border-dark">Изтриване</button>
                            </form>
                        </div>
                    </article>
                }
            </section>
            <partial name="_PagesNavigation" view-data="ViewData">
    </main>
}

src/MVCProject.Web/Areas/Admin/Views/Article/Edit.cshtml
@model ArticleEditModel

@{
    ViewData["Title"] = "Редактирай публикация";
}

<link href="~/css/froala/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />

<header>
    <h3 class="text-center mb-3">Редактирай публикация</h3>
</header>
<main>
    <div class="add-article-container">
        <form asp-area="Admin" asp-controller="Article" asp-action="Edit" method="post" class="add-article-flex-item text-center">
            <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />
            <div>
                <label asp-for="@Model.Title" class="mt-3">Заглавие</label>
                <input type="text" asp-for="@Model.Title" class="form-control" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="@Model.Content" class="mt-3">Съдържание</label>
                <textarea id="content" name="content">@Model.Content</textarea>
                <span asp-validation-for="@Model.Content" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="@Model.Author" class="mt-3">Автор(и)</label>
                <input type="text" asp-for="@Model.Author" class="form-control" />
                <span asp-validation-for="@Model.Author" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="@Model.SourceUrl" class="mt-3">URL на източник</label>
                <input type="text" asp-for="@Model.SourceUrl" class="form-control" />
                <span asp-validation-for="@Model.SourceUrl" class="text-danger"></span>
            </div>

            <input type="submit" value="Запази" class="btn btn-success mt-3" />
        </form>
    </div>
</main>

<script type="text/javascript" src="~/js/froala/froala_editor.pkgd.min.js"></script>
<script type="text/javascript" src="~/js/InitializeFroala.js"></script>