src/MVCProject.Web/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;

namespace MigraineDiary.Web.Controllers
{
    [AllowAnonymous]
    public class ContactsController : Controller
    {
        private readonly IMessageService messageService;

        public ContactsController(IMessageService messageService)
        {
            this.messageService = messageService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(MessageAddModel addModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addModel);
            }

            await this.messageService.AddAsync(addModel);

            // Get controller's name and action's name without using magic strings.
            string actionName = nameof(ContactsController.Info);
            string controllerName = nameof(ContactsController).Substring(0, nameof(ContactsController).Length - "Controller".Length);

            return RedirectToAction(actionName, controllerName);
        }

        [HttpGet]
        public IActionResult Info() 
        {
            return View();
        }
    }
}

src/MVCProject.Web/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;
using System.Security.Claims;

namespace MigraineDiary.Web.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class PatientsController : Controller
    {
        private readonly IPatientService patientService;
        private readonly IHeadacheService headacheService;
        private readonly IHIT6ScaleService hit6ScaleService;
        private readonly IZungScaleForAnxietyService zungScaleForAnxietyService;

        public PatientsController(IPatientService patientService, 
                                 IHeadacheService headacheService, 
                                IHIT6ScaleService hit6ScaleService,
                      IZungScaleForAnxietyService zungScaleForAnxietyService)
        {
            this.patientService = patientService;
            this.headacheService = headacheService;
            this.hit6ScaleService = hit6ScaleService;
            this.zungScaleForAnxietyService = zungScaleForAnxietyService;

        }

        [HttpGet]
        public async Task<IActionResult> MyPatients()
        {
            // Get logged user's ID
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get all users who shared headache or scale with logged user in role "Doctor".
            PatientViewModel[] patients = await this.patientService.GetAllPatientsAsync(currentUserId);

            return View(patients);
        }

        [HttpGet]
        public async Task<IActionResult> Headaches(string patientId, int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering.
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get logged user's ID.
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get shared headaches with logged user in role "Doctor".
            PaginatedList<SharedHeadacheViewModel> sharedHeadachesViewModel = await this.headacheService.GetSharedHeadachesAsync(currentUserId, patientId, pageIndex, pageSize, orderByDate);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(sharedHeadachesViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> HIT6Scales(string patientId, int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering.
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get logged user's ID.
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get shared headaches with logged user in role "Doctor".
            PaginatedList<SharedHIT6ScaleViewModel> sharedHIT6ScalesViewModel = await this.hit6ScaleService.GetSharedScalesAsync(currentUserId, patientId, pageIndex, pageSize, orderByDate);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(sharedHIT6ScalesViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ZungScales(string patientId, int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering.
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get logged user's ID.
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get shared headaches with logged user in role "Doctor".
            PaginatedList<SharedZungScaleForAnxietyViewModel> sharedZungScalesViewModel = await this.zungScaleForAnxietyService.GetSharedScalesAsync(currentUserId, patientId, pageIndex, pageSize, orderByDate);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(sharedZungScalesViewModel);
        }
    }
}

src/MVCProject.Web/Controllers/TrialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;
using System.Security.Claims;
using System.Net.Mime;

namespace MigraineDiary.Web.Controllers
{
    [Authorize(Roles = "Admin,Doctor")]
    public class TrialController : Controller
    {
        private IWebHostEnvironment environment;
        private readonly IClinicalTrialService trialService;

        public TrialController(IWebHostEnvironment environment,
                             IClinicalTrialService trialService)
        {
            this.environment = environment;
            this.trialService = trialService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get all trials
            PaginatedList<ClinicalTrialViewModel> trials = await this.trialService.GetAllTrialsAsync(pageIndex, pageSize, orderByDate);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(trials);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ClinicalTrialAddModel model = new ClinicalTrialAddModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ClinicalTrialAddModel addModel)
        {
            // Reset custom added model errors for next validation cycle.
            // If reset is skipped even with correct data submission on next user input, ModelState continues to not be valid!
            ModelState[nameof(addModel.TrialAgreementDocument)]?.Errors.Clear();
            ModelState[nameof(addModel.TrialAgreementDocument)]?.Errors.Clear();
            ModelState[nameof(addModel.Practicioners)]?.Errors.Clear();

            if (!ModelState.IsValid)
            {
                // Add custom validation if ModelState is not valid.
                if (addModel.TrialAgreementDocument == null)
                {
                    ModelState.AddModelError(nameof(addModel.TrialAgreementDocument), "Необходимо е да приложите файл с описание и информирано съгласие.");
                }

                if (addModel.Practicioners.Any(x => x.FirstName == null))
                {
                    ModelState.AddModelError(nameof(addModel.Practicioners), "Необходимо е да въведете име и фамилия на изследователите.");
                }

                return View();
            }

            // Add custom error messages for Practicioner's first name and last name length.

            if (addModel.Practicioners.Any(x => x.FirstName.Length < 3 || x.FirstName.Length > 30) ||
                addModel.Practicioners.Any(x => x.Lastname.Length < 3 || x.Lastname.Length > 30))
            {
                ModelState.AddModelError(nameof(addModel.Practicioners), "Дължината на името трябва да бъде между 3 и 30 символа.");

                return View();
            }
            
            // Add custom validation for file format extension and file size.

            // Get uploaded file's extension.
            string fileFormatExtension = addModel.TrialAgreementDocument.FileName.Split('.')[1];

            // Check if uploaded file isn't pdf.
            if (fileFormatExtension != "pdf")
            {
                ModelState.AddModelError(nameof(addModel.TrialAgreementDocument), "Не са позволени файлови формати, различни от pdf.");

                return View();
            }

            // Check if file is bigger than 25 MB.
            if (addModel.TrialAgreementDocument.Length > 25000000)
            {
                ModelState.AddModelError(nameof(addModel.TrialAgreementDocument), "Големината на файла не може да надвишава 25 MB.");

                return View();
            }

            // Generate unique file name.
            string fileName = this.trialService.GenerateUniqueFileName(fileFormatExtension);

            // Save file in filesystem.
            string saveDirectory = Path.Combine(environment.WebRootPath, fileName);
            using FileStream fs = new FileStream(saveDirectory, FileMode.Create);
            await addModel.TrialAgreementDocument.CopyToAsync(fs);

            // Get current user ID
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Save clinical trial in database.
            await this.trialService.AddAsync(addModel, fileName, userId);

            // Get controller's name and action's name without using magic strings.
            string actionName = nameof(TrialController.Index);
            string controllerName = nameof(TrialController).Substring(0, nameof(TrialController).Length - "Controller".Length);

            return RedirectToAction(actionName, controllerName);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Download(string documentName)
        {
            string filePath = Path.Combine(environment.WebRootPath, documentName);

            if (System.IO.File.Exists(filePath))
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

                return File(fileBytes, MediaTypeNames.Application.Pdf, "Информирано съгласие.pdf");
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> MyTrials(int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get logged user's ID
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get all trials registered by this specific user.
            PaginatedList<ClinicalTrialViewModel> trials = await this.trialService.GetAllTrialsAsync(pageIndex, pageSize, orderByDate, userId);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(trials);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string trialId, string creatorId)
        {
            // Get logged user Id.
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Check for parameter tampering.
            if (!ModelState.IsValid || creatorId != userId)
            {
                return BadRequest();
            }

            // Get trial which is going to be edited.
            ClinicalTrialEditModel trialModel = await this.trialService.GetByIdAsync(trialId, userId);

            return View(trialModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClinicalTrialEditModel editModel)
        {
            // Reset custom added model errors for next validation cycle.
            // If reset is skipped even with correct data submission on next user input, ModelState continues to not be valid!
            ModelState[nameof(editModel.TrialAgreementDocument)]?.Errors.Clear();
            ModelState[nameof(editModel.Practicioners)]?.Errors.Clear();

            if (!ModelState.IsValid)
            {
                // Add custom validation if ModelState is not valid.
                if (editModel.Practicioners.Any(x => x.FirstName == null) ||
                    editModel.Practicioners.Any(x => x.Lastname == null))
                {
                    ModelState.AddModelError(nameof(editModel.Practicioners), "Необходимо е да въведете име и фамилия на изследователите.");
                }

                return View(editModel);
            }

            // Add custom error messages for Practicioner's first name and last name length.

            if (editModel.Practicioners.Any(x => x.FirstName.Length < 3 || x.FirstName.Length > 30) ||
                editModel.Practicioners.Any(x => x.Lastname.Length < 3 || x.Lastname.Length > 30))
            {
                ModelState.AddModelError(nameof(editModel.Practicioners), "Дължината на името трябва да бъде между 3 и 30 символа.");

                return View(editModel);
            }

            // Add custom validation for file format extension and file size.

            // Check if user has uploaded new file.
            if (editModel.TrialAgreementDocument != null)
            {
                // Get uploaded file's extension.
                string fileFormatExtension = editModel.TrialAgreementDocument.FileName.Split('.')[1];

                // Check if uploaded file isn't pdf.
                if (fileFormatExtension != "pdf")
                {
                    ModelState.AddModelError(nameof(editModel.TrialAgreementDocument), "Не са позволени файлови формати, различни от pdf.");

                    return View(editModel);
                }

                // Check if file is bigger than 25 MB.
                if (editModel.TrialAgreementDocument.Length > 25000000)
                {
                    ModelState.AddModelError(nameof(editModel.TrialAgreementDocument), "Големината на файла не може да надвишава 25 MB.");

                    return View(editModel);
                }

                // Create delete path.

src/MVCProject.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["currentUserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Migraine Diary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MigraineDiary.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body onload="getNotification()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="color: white; text-shadow: 2px 2px 4px #000000;">Migraine Diary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <div class="btn-group">
                                <a href="#" class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Дневник
                                </a>
                                <div class="dropdown-menu bg-warning mt-2">
                                    <a class="dropdown-item" asp-area="" asp-controller="Headache" asp-action="GetAll" asp-route-currentUserId=@ViewData["currentUserId"]>Моите главоболия</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Headache" asp-action="Add" asp-route-currentUserId=@ViewData["currentUserId"]>Регистрирай главоболие</a>
                                </div>
                            </div>
                        </li>
                        
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <div class="btn-group">
                                    <a href="#" class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Скали за самооценка
                                    </a>
                                    <div class="dropdown-menu bg-warning mt-2">
                                        <a class="dropdown-item" asp-area="" asp-controller="Scales" asp-action="MyHIT6Scales" asp-route-currentUserId=@ViewData["currentUserId"]>Моите HIT-6 скали</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Scales" asp-action="AddHIT6Scale" asp-route-currentUserId=@ViewData["currentUserId"]>Добави HIT-6 скала</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Scales" asp-action="MyZungScales" asp-route-currentUserId=@ViewData["currentUserId"]>Моите скали на Zung</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Scales" asp-action="AddZungScale" asp-route-currentUserId=@ViewData["currentUserId"]>Добави скала на Zung</a>
                                    </div>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Публикации</a>
                        </li>
                        @if (User.IsInRole("Doctor") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <div class="btn-group">
                                    <a href="#" class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Клинични проучвания
                                    </a>
                                    <div class="dropdown-menu bg-warning mt-2">
                                        <a class="dropdown-item" asp-area="" asp-controller="Trial" asp-action="Add">Добави</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Trial" asp-action="Index">Всички проучвания</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Trial" asp-action="MyTrials">Моите проучвания</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Patients" asp-action="MyPatients">Пациенти</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Trial" asp-action="Index">Клинични проучвания</a>
                            </li>
                        }
                    </ul>
                    @if (User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Admin" asp-controller="Admin" asp-action="Index">Админ панел</a>
                            </li>
                        </ul>
                    }
                    <partial name="_NotificationsPartial" />
                    <partial name="_LoginPartial" />
                    <span id="notification-icon" class="notification-icon"></span>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer id="footer" class="border-top bg-primary h-5 text-white">
        <div class="nav-bar-container">
            <ul class="footer-links">
                <li>
                    <a asp-controller="Home" asp-action="TermsAndConditions" class="test">Общи условия</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="Privacy" class="test">Поверителност</a>
                </li>
                <li>
                    <a asp-controller="Contacts" asp-action="Index">Контакти</a>
                </li>
            </ul>
            <div class="row mb-3">
                Migraine diary - ASP.NET project by Daniel Dianov, M.D. &copy; 2023 - @DateTime.UtcNow.Year
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notifications.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MVCProject.Web/Views/Shared/_NotificationsPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<ul class="navbar-nav">
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item" style="margin: 0 10px">
            <a asp-area="Admin" asp-controller="Admin" asp-action="Inbox" class="fa-regular fa-envelope fa-2xl" title="Messages" style="color:white; text-decoration: none;"></a>
        </li>
    }
    else
    {
        @if (SignInManager.IsSignedIn(User))
        {
            <li class="nav-item" style="margin: 0 10px">
                <i class="fa-regular fa-bell fa-xl" style="color: white;"></i>
            </li>
        }
    }
</ul>

src/MVCProject.Web/Views/Shared/_PageItemsOrderingNavigation.cshtml
<nav id="ordering-navigation">
    <div>
        <form asp-controller=@ViewData["PartialViewController"] asp-action=@ViewData["PartialViewAction"] method="get" class="page-sorting-container">
            <div>
                <label name="pageSize">@ViewData["itemsType"] на страница:</label>
                <select name="pageSize" onchange="submit();">
                    @if ((int)ViewData["pageSize"]! == 1)
                    {
                        <option value="1" selected>1</option>
                    }
                    else
                    {
                        <option value="1">1</option>
                    }

                    @if ((int)ViewData["pageSize"]! == 5)
                    {
                        <option value="5" selected>5</option>
                    }
                    else
                    {
                        <option value="5">5</option>
                    }

                    @if ((int)ViewData["pageSize"]! == 10)
                    {
                        <option value="10" selected>10</option>
                    }
                    else
                    {
                        <option value="10">10</option>
                    }
                </select>
            </div>
            
            <div>
                <label name="orderByDate">Подреди по:</label>
                <select name="orderByDate" onchange="submit();">
                    @if ((string)ViewData["orderByDate"]! == "NewestFirst")
                    {
                        <option value="NewestFirst" selected>Най-нови</option>
                    }
                    else
                    {
                        <option value="NewestFirst">Най-нови</option>
                    }

                    @if ((string)ViewData["orderByDate"]! == "OldestFirst")
                    {
                        <option value="OldestFirst" selected>Най-стари</option>
                    }
                    else
                    {
                        <option value="OldestFirst">Най-стари</option>
                    }
                </select>
            </div>
        </form>
    </div>
</nav>

src/MVCProject.Web/Views/Shared/_SearchAndSharePartial.cshtml
@model IEnumerable<DoctorViewModel>

@if (Model.Count() > 0)
{
    <p id="shared-paragraph-@ViewData["entityCounter"]">
        <span>Споделено с: </span>
        @{
            DoctorViewModel[] orderedDoctors = @Model.OrderBy(x => x.FirstName).ThenBy(x => x.LastName).ToArray();
        }
        @for (int i = 0; i < orderedDoctors.Length; i++)
        {
            if (i < orderedDoctors.Length - 1)
            {
                <span>Д-р @orderedDoctors[i].FirstName @orderedDoctors[i].LastName, </span>
            }
            else
            {
                <span>Д-р @orderedDoctors[i].FirstName @orderedDoctors[i].LastName</span>
            }
        }
    </p>
}
else
{
    <p id="shared-paragraph-@ViewData["entityCounter"]" style="display: none;"><span>Споделено с: </span></p>
}

<div>
    <span>Сподели с: </span>
    <input type="text" id="searchBar-@ViewData["entityCounter"]" placeholder="Намери лекар..." oninput="searchDoctor(@ViewData["entityCounter"]);" class="searchBar" />
    <span id="share-entity-btn-@ViewData["entityCounter"]" class="btn btn-success share-headache-btn">Сподели</span>
    <div id="searchResults-@ViewData["entityCounter"]"></div>
</div>
<div class="mt-2">
    <button type="button" class="btn btn-primary" onclick="removeSearchResults(@ViewData["entityCounter"]);" style="margin-left: 132px;">Изчисти</button>
</div>