src/MVCProject.Web/Controllers/HeadacheController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Data;
using MigraineDiary.Data.DbModels;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;
using System.Security.Claims;

namespace MigraineDiary.Web.Controllers
{
    [Authorize]
    public class HeadacheController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext dbContext;
        private readonly IHeadacheService headacheService;

        public HeadacheController(UserManager<ApplicationUser> userManager,
                                          ApplicationDbContext dbContext,
                                              IHeadacheService headacheService)
        {
            this.userManager = userManager;
            this.dbContext = dbContext;
            this.headacheService = headacheService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            HeadacheAddFormModel model = new HeadacheAddFormModel();

            ViewData["currentUserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(HeadacheAddFormModel addModel, string currentUserId)
        {
            // Get current user's Id if ModelState is not valid and it's needed to be routed.
            // If not routed on next submission currentUserId is null and ModelState is not valid again.
            ViewData["currentUserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Calculate headache duration so it can be custom validated.
            Dictionary<string, int> headacheDuration = this.headacheService.CalculateDuration(addModel.Onset, addModel.EndTime);

            // Custom headache validations.

            // Check if form is submitted with default value which is not DateTime (user didn't select value).
            if (ModelState["Onset"] != null)
            {
                if (ModelState["Onset"]!.Errors.Any(x => x.ErrorMessage == "The value '' is invalid."))
                {
                    // Remove default ErrorMessage.
                    ModelState.Remove("Onset");

                    // Add custom ErrorMessage.
                    ModelState.AddModelError(nameof(addModel.Onset), "Необходимо е да въведете начало на главоболието.");
                }
            }

            // Check if form is submitted with default value which is not DateTime (user didn't select value).
            if (ModelState["EndTime"] != null)
            {
                if (ModelState["EndTime"]!.Errors.Any(x => x.ErrorMessage == "The value '' is invalid."))
                {
                    // Remove default ErrorMessage.
                    ModelState.Remove("EndTime");

                    // Add custom ErrorMessage.
                    ModelState.AddModelError(nameof(addModel.EndTime), "Необходимо е да въведете край на главоболието.");
                }
            }

            // If headache ended before it started scenario.
            if (headacheDuration["Days"] < 0 ||
                headacheDuration["Hours"] < 0 ||
                headacheDuration["Minutes"] < 0)
            {
                ModelState.AddModelError(nameof(addModel.EndTime), "Края на главоболието не може да бъде преди началото му.");
            }
            // Else if headache ended at the moment it just started scenario.
            else if (headacheDuration["Days"] <= 0 &&
                     headacheDuration["Hours"] <= 0 &&
                     headacheDuration["Minutes"] == 0)
            {
                ModelState.AddModelError(nameof(addModel.EndTime), "Началото и краят на главоболието не могат да съвпадат.");
            }

            // Check if form is submitted without selecting severity.
            if (addModel.Severity == 0)
            {
                ModelState.AddModelError(nameof(addModel.Severity), "Необходимо е да посочите сила на главоболието.");
            }

            // Check if hidden inputs values are submitted (user didn't chose answer).
            if (addModel.Photophoby == "noAnswer")
            {
                ModelState.AddModelError(nameof(addModel.Photophoby), "Необходимо е да посочите отговор.");
            }

            if (addModel.Phonophoby == "noAnswer")
            {
                ModelState.AddModelError(nameof(addModel.Phonophoby), "Необходимо е да посочите отговор.");
            }

            if (addModel.Nausea == "noAnswer")
            {
                ModelState.AddModelError(nameof(addModel.Nausea), "Необходимо е да посочите отговор.");
            }

            if (addModel.Vomiting == "noAnswer")
            {
                ModelState.AddModelError(nameof(addModel.Vomiting), "Необходимо е да посочите отговор.");
            }

            if (addModel.Aura == "noAnswer")
            {
                ModelState.AddModelError(nameof(addModel.Aura), "Необходимо е да посочите отговор.");
            }

            for (int i = 0; i < addModel.MedicationsTaken.Count; i++)
            {
                if (ModelState[$"MedicationsTaken[{i}].SinglePillDosage"] != null &&
                    ModelState[$"MedicationsTaken[{i}].SinglePillDosage"]!.Errors.Any(e => e.ErrorMessage == "The value '' is invalid."))
                {
                    // Remove default ErrorMessage.
                    ModelState.Remove($"MedicationsTaken[{i}].SinglePillDosage");

                    // Add custom ErrorMessage.
                    ModelState.AddModelError($"MedicationsTaken[{i}].SinglePillDosage", "Необходимо е да въведете доза на медикамента.");

                    // Set custom value for view logic to escape default behavior.
                    addModel.MedicationsTaken[i].SinglePillDosage = int.MinValue;
                }

                if (ModelState[$"MedicationsTaken[{i}].NumberOfTakenPills"] != null &&
                    ModelState[$"MedicationsTaken[{i}].NumberOfTakenPills"]!.Errors.Any(e => e.ErrorMessage == "The value '' is invalid."))
                {
                    // Remove default ErrorMessage.
                    ModelState.Remove($"MedicationsTaken[{i}].NumberOfTakenPills");

                    // Add custom ErrorMessage.
                    ModelState.AddModelError($"MedicationsTaken[{i}].NumberOfTakenPills", "Необходимо е да въведете брой приети таблетки.");

                    // Set custom value for view logic to escape default behavior.
                    addModel.MedicationsTaken[i].NumberOfTakenPills = int.MinValue;
                }
            }

            if (!ModelState.IsValid)
            {
                return View(addModel);
            }

            // Add headache.
            await this.headacheService.AddAsync(addModel, headacheDuration, currentUserId);

            // Get controller name and action name without using magic strings.
            string actionName = nameof(HeadacheController.GetAll);
            string controllerName = nameof(HeadacheController).Substring(0, nameof(HeadacheController).Length - "Controller".Length);

            return RedirectToAction(actionName, controllerName);
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering.
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get current user's Id
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["currentUserId"] = userId;

            // Get paginated collection of view model according to given criteria.
            PaginatedList<RegisteredHeadacheViewModel> registeredHeadachesViewModel = await headacheService.GetRegisteredHeadachesAsync(userId, pageIndex, pageSize, orderByDate);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(registeredHeadachesViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> SearchDoctor(string name)
        {
            if (name == null || name == string.Empty)
            {
                return BadRequest();
            }

            DoctorViewModel[] doctors = await this.headacheService.GetDoctorUsersByNameAsync(name);

            return Json(doctors);
        }

        [HttpPost]
        public async Task<IActionResult> ShareHeadache([FromBody] SharedHeadacheAddModel headache)
        {
            if (String.IsNullOrEmpty(headache.DoctorID) == false)
            {
                try
                {
                    await this.headacheService.Share(headache.HeadacheID, headache.DoctorID);

                    return Ok("Successfuly shared!");
                }
                catch (ArgumentException ex)
                {
                    // TODO: Log exception.
                    return BadRequest(ex.Message);
                }
            }

            return BadRequest();
        }
    }
}

src/MVCProject.Web/Views/Headache/Add.cshtml
@model HeadacheAddFormModel

@{
    ViewData["Title"] = "Регистрирай главоболие";
}

<div class="row text-center">
    <form asp-controller="Headache" asp-action="Add" asp-route-currentUserId=@ViewData["currentUserId"] method="post">
        <div class="mb-3">
            <label asp-for=@Model.Onset>Начало на главоболието:</label> <br />
            @*Escape default behaviour (populating the field with default datetime value on HttpGet)*@
            @if (Model.Onset == DateTime.MinValue)
            {
                <input type="datetime-local" asp-for="@Model.Onset" min="2022-01-01T00:00" max="2099-01-01T00:00" value="" /> <br />
            }
            else
            {
                <input type="datetime-local" asp-for="@Model.Onset" min="2022-01-01T00:00" max="2099-01-01T00:00" /> <br />
            }
            <span asp-validation-for="@Model.Onset" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <Label asp-for="@Model.EndTime">Край на главоболието:</Label> <br />
            @*Escape default behaviour (populating the field with default datetime value on HttpGet)*@
            @if (Model.EndTime == DateTime.MinValue)
            {
                <input type="datetime-local" asp-for="@Model.EndTime" min="2022-01-01T00:00" max="2099-01-01T00:00" value="" /> <br />
            }
            else
            {
                <input type="datetime-local" asp-for="@Model.EndTime" min="2022-01-01T00:00" max="2099-01-01T00:00" /> <br />
            }
            <span asp-validation-for="@Model.EndTime" class="text-danger"></span>
        </div>
        <div class="mb-4">
            <label asp-for="@Model.LocalizationSide">Посочете в коя част на главата изпитвахте болка:</label> <br />
            <textarea asp-for="@Model.LocalizationSide" rows="5" cols="80" placeholder="Левостранно/десностранно/тилно/челно..."></textarea> <br />
            <span asp-validation-for="@Model.LocalizationSide" class="text-danger"></span>
        </div>
        <div class="mb-4">
            <label asp-for="@Model.PainCharacteristics">Опишете характеристиката на болката:</label> <br />
            <textarea asp-for="@Model.PainCharacteristics" rows="5" cols="80" placeholder="Пулсираща/стягаща/остра/постепенно настъпваща..."></textarea> <br />
            <span asp-validation-for="@Model.PainCharacteristics" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Severity" style="margin-right: 15px;">Посочете силата на главоболието от 1 до 10:</label>
            <select asp-for="@Model.Severity">
                <option value="0" selected="selected">--</option>
                @for (int i = 1; i <= 10; i++)
                {
                    <option value="@i">@i</option>
                }
            </select> <br />
            <div style="display: flex; justify-content: center;">
                <div class="VAS-description">
                    <i style="font-size: 12px;">
                        <span>0 - липса на болка</span> <br />
                        <span>10 - най-силната болка, която си представяте, че съществува.</span>
                    </i>
                </div>
            </div>
            <span asp-validation-for="@Model.Severity" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Photophoby">Главоболието Ви влошаваше ли се от светлината?</label> <br />
            <input type="radio" asp-for="@Model.Photophoby" name="Photophoby" value="noAnswer" checked="checked" class="d-none" />
            <span>Да</span>
            <input type="radio" asp-for="@Model.Photophoby" name="Photophoby" value="true" />
            <span>Не</span>
            <input type="radio" asp-for="@Model.Photophoby" name="Photophoby" value="false" /> <br />
            <span asp-validation-for="@Model.Photophoby" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Phonophoby">Главоболието Ви влошаваше ли се от шума?</label> <br />
            <input type="radio" asp-for="@Model.Phonophoby" value="noAnswer" checked class="d-none" />
            <span>Да</span>
            <input type="radio" asp-for="@Model.Phonophoby" value="true" />
            <span>Не</span>
            <input type="radio" asp-for="@Model.Phonophoby" value="false" /> <br />
            <span asp-validation-for="@Model.Phonophoby" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Nausea">Изпитвахте ли гадене?</label> <br />
            <input type="radio" asp-for="@Model.Nausea" value="noAnswer" checked class="d-none" />
            <span>Да</span>
            <input type="radio" asp-for="@Model.Nausea" value="true" />
            <span>Не</span>
            <input type="radio" asp-for="@Model.Nausea" value="false" /> <br />
            <span asp-validation-for="@Model.Nausea" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Vomiting">Имахте ли повръщане?</label> <br />
            <input type="radio" asp-for="@Model.Vomiting" value="noAnswer" checked class="d-none" />
            <span>Да</span>
            <input type="radio" asp-for="@Model.Vomiting" value="true" />
            <span>Не</span>
            <input type="radio" asp-for="@Model.Vomiting" value="false" /> <br />
            <span asp-validation-for="@Model.Vomiting" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Aura">Имахте ли аура?</label> <br />
            <input type="radio" asp-for="@Model.Aura" value="noAnswer" checked class="d-none" />
            @if (Model.Aura != "true")
            {
                <span>Да</span>
                <input type="radio" asp-for="@Model.Aura" value="true" class="aura-yes" onclick="addAuraDescription();" />
                <span>Не</span>
                <input type="radio" asp-for="@Model.Aura" value="false" class="aura-no" /> <br />
            }
            else
            {
                <span>Да</span>
                <input type="radio" asp-for="@Model.Aura" value="true" class="aura-yes" />
                <span>Не</span>
                <input type="radio" asp-for="@Model.Aura" value="false" class="aura-no" onclick="removeAuraDescription();" /> <br />
            }
            <span asp-validation-for="@Model.Aura" class="text-danger"></span>
        </div>
        <div class="mb-3 aura-description">
            @if (Model.Aura == "true")
            {
                <label asp-for="@Model.AuraDescriptionNotes">Oпишете аурата си:</label> <br>
                <textarea asp-for="@Model.AuraDescriptionNotes" rows="5" cols="80"></textarea>
            }
            <span asp-validation-for="@Model.AuraDescriptionNotes" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Triggers">Опишете фактори, които са провокирали мигренозния пристъп:</label> <br />
            <textarea asp-for="@Model.Triggers" rows="5" cols="80" placeholder="Определени храни, напитки и др."></textarea> <br />
            <span asp-validation-for="@Model.Triggers" class="text-danger"></span>
        </div>
        @if (Model.MedicationsTaken.Count == 0)
        {
            <div class="mb-3" id="medication-usage">
                <label for="medication-usage">Употребихте ли медикамент(и)?</label> <br />
                <span>Да</span>
                <input type="radio" id="medication-usage-yes" name="medication-usage" value="yes" onclick="createAddButton();" oninvalid="this.setCustomValidity('Необходимо е да посочите използвахте ли медикамент(и).')">
                <span>Не</span>
                <input type="radio" id="medication-usage-no" name="medication-usage" value="no">
            </div>
            <div id="used-medications-container" class="mb-3"></div>
            <div id="add-medication-button" class="mb-3"></div>
        }
        else
        {
            <div class="mb-3" id="medication-usage">
                <label for="medication-usage">Употребихте ли медикамент(и)?</label> <br />
                <span>Да</span>
                <input type="radio" id="medication-usage-yes" name="medication-usage" value="yes" checked oninvalid="this.setCustomValidity('Необходимо е да посочите използвахте ли медикамент(и).')">
                <span>Не</span>
                <input type="radio" id="medication-usage-no" name="medication-usage" value="no" onclick="removeAddButton();">
            </div>
            <div id="used-medications-container" class="mb-3">
                @for (int i = 0; i < Model.MedicationsTaken.Count; i++)
                {
                    <div id="medication-@i">
                        <input type="text" name="MedicationsTaken[@i].Name" value="@Model.MedicationsTaken[i].Name" placeholder="Име на медикамента" class="text-center" style="margin-right: 20px;">
                        @if (Model.MedicationsTaken[@i].SinglePillDosage < 0)
                        {
                            <input type="number" name="MedicationsTaken[@i].SinglePillDosage" value="" placeholder="Доза" class="text-center" step="0.25" style="margin-right: 20px;">
                        }
                        else
                        {
                            <input type="number" name="MedicationsTaken[@i].SinglePillDosage" value="@Model.MedicationsTaken[i].SinglePillDosage" placeholder="Доза" class="text-center" step="0.25" style="margin-right: 20px;">
                        }
                        <select name="MedicationsTaken[@i].Units" class="mb-3" style="margin-right: 20px;">
                            @if (Model.MedicationsTaken[i].Units == "mcg")
                            {
                                <option value="mcg" selected="selected">mcg</option>
                                <option value="mg">mg</option>
                                <option value="g">g</option>
                                <option value="ml">ml</option>
                            }
                            else if (Model.MedicationsTaken[i].Units == "mg")
                            {
                                <option value="mcg">mcg</option>
                                <option value="mg" selected="selected">mg</option>
                                <option value="g">g</option>
                                <option value="ml">ml</option>
                            }
                            else if (Model.MedicationsTaken[i].Units == "g")
                            {
                                <option value="mcg">mcg</option>
                                <option value="mg">mg</option>
                                <option value="g" selected="selected">g</option>
                                <option value="ml">ml</option>
                            }
                            else if (Model.MedicationsTaken[i].Units == "ml")
                            {
                                <option value="mcg">mcg</option>
                                <option value="mg">mg</option>
                                <option value="g">g</option>
                                <option value="ml" selected="selected">ml</option>
                            }
                        </select>
                        @if (Model.MedicationsTaken[i].NumberOfTakenPills < 0)
                        {
                            <input type="number" name="MedicationsTaken[@i].NumberOfTakenPills" value="" placeholder="Брой приети таблетки" class="text-center" step="0.25" style="width: 200px;">
                        }
                        else
                        {
                            <input type="number" name="MedicationsTaken[@i].NumberOfTakenPills" value="@Model.MedicationsTaken[i].NumberOfTakenPills" placeholder="Брой приети таблетки" class="text-center" step="0.25" style="width: 200px;">
                        }
                        <button type="button" id="remove-medication-@i" onclick="removeMedication('medication-@i')" class="btn btn-danger" style="margin-left: 20px;">Премахни</button> <br />
                        <div class="d-flex flex-column mb-4">
                            <span asp-validation-for="@Model.MedicationsTaken[i].Name" class="text-danger"></span>
                            <span asp-validation-for="@Model.MedicationsTaken[i].SinglePillDosage" class="text-danger"></span>
                            <span asp-validation-for="@Model.MedicationsTaken[i].Units" class="text-danger"></span>
                            <span asp-validation-for="@Model.MedicationsTaken[i].NumberOfTakenPills" class="text-danger"></span>
                        </div>
                    </div>
                }
            </div>
            <div id="add-medication-button" class="mb-3">
                <button type="button" id="addMedication" class="btn btn-success" onclick="аddMedication();">Добави медикамент</button>
            </div>
        }
        <input type="submit" class="btn btn-primary" value="Добави" />
    </form>
</div>
<script src="~/js/addHeadache.js"></script>

src/MVCProject.Web/Views/Headache/GetAll.cshtml
@model PaginatedList<RegisteredHeadacheViewModel>

@{
    ViewData["Title"] = "Headaches";
    ViewData["PartialViewController"] = "Headache";
    ViewData["PartialViewAction"] = "GetAll";
    ViewData["itemsType"] = "Главоболия";
    ViewData["entityCounter"] = 1;

    int headacheCounter = 1;
    string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}

<section>
    @if (Model.Count > 0)
    {
        <h3 class="text-center">Регистрирани главоболия</h3>
        <partial name="_PageItemsOrderingNavigation" view-data="ViewData" />
        <div class="container mt-4">
            <div class="row">
                @foreach (var headache in Model)
                {
                    <h4 class="text-center article-title">Главоболие № @(headacheCounter * Model.CurrentPageIndex)</h4>
                    <hr />
                    <input type="hidden" id="entityID-@headacheCounter" entitytype="Headache" value="@headache.Id">
                    <p>
                        Начало на главоболието: @headache.Onset.TimeOfDay.ToString().Substring(0, 5) ч. на
                        @headache.Onset.ToShortDateString()
                    </p>
                    <p>
                        Край на главоболието: @headache.EndTime.TimeOfDay.ToString().Substring(0, 5) ч. на
                        @headache.EndTime.ToShortDateString()
                    </p>
                    <p>Продължителност на главоболието: @headache.DurationDays @(headache.DurationDays == 1 ? "ден" : "дни"), @headache.DurationHours @(headache.DurationHours == 1 ? "час" : "часа") и @headache.DurationMinutes минути</p>
                    <p>Сила на болката (0-10): @headache.Severity</p>
                    <p>Локализация на болката: @headache.LocalizationSide</p>
                    <p>Характеристика на болката: @headache.PainCharacteristics</p>
                    <p>Фотофобия: @(headache.Photophoby == true ? "да" : "не")</p>
                    <p>Фонофобия: @(headache.Phonophoby == true ? "да" : "не")</p>
                    <p>Гадене: @(headache.Nausea == true ? "да" : "не")</p>
                    <p>Повръщане: @(headache.Vomiting == true ? "да" : "не")</p>
                    <p>Наличие на аура: @(headache.Vomiting == true ? "да" : "не")</p>

                    @if (headache.Aura == true)
                    {
                        <p>Описание на аурата: @(headache.AuraDescriptionNotes != null ? headache.AuraDescriptionNotes : "липсва oписание") </p>
                    }

                    <p>Провокиращи главоболието фактори: @(headache.Triggers != null ? headache.Triggers : "липсват данни")</p>

                    @if (headache.UsedMedications.Count() == 0)
                    {
                        <p>Употребени медикаменти: липсват данни</p>
                    }
                    else
                    {
                        <p>Употребени медикаменти:</p>
                        <ul style="margin-left: 50px">
                            @for (int i = 0; i < headache.UsedMedications.Count(); i++)
                            {
                                var medication = @headache.UsedMedications.ElementAt(i);

                                <li>@medication.Name @medication.SinglePillDosage @medication.Units - @($"{@medication.DosageTaken:F2}") @medication.Units</li>
                            }
                        </ul>
                    }

                    <partial name="_SearchAndSharePartial" model="@headache.Doctors" view-data="ViewData" />
                    headacheCounter++;
                    ViewData["entityCounter"] = headacheCounter;
                }
            </div>
        </div>
        <hr />
        <partial name="_PagesNavigation" view-data="ViewData" />
    }
    else
    {
        <div>
            <p>Изглежда все още нямате регистрирани главоболия. Защо не регистрирате първото си главоболие от <a asp-controller="Headache" asp-action="Add" asp-route-id=@currentUserId>тук</a>?</p>
        </div>
    }
</section>

@section Scripts {
    <script src="~/js/search.js" asp-append-version="true"></script>
    <script src="~/js/shareHeadache.js" asp-append-version="true"></script>
}