src/MVCProject.Web/Controllers/ScalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraineDiary.Services.Contracts;
using MigraineDiary.ViewModels;
using System.Security.Claims;

namespace MigraineDiary.Web.Controllers
{
    [Authorize]
    public class ScalesController : Controller
    {
        private readonly IHIT6ScaleService HIT6ScaleService;
        private readonly IZungScaleForAnxietyService ZungScaleForAnxietyService;

        public ScalesController(IHIT6ScaleService HIT6scaleService,
                      IZungScaleForAnxietyService ZungScaleForAnxietyService)
        {
            this.HIT6ScaleService = HIT6scaleService;
            this.ZungScaleForAnxietyService = ZungScaleForAnxietyService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            // Get controller's name and action's name without using magic strings.
            string actionName = nameof(ScalesController.AddHIT6Scale);
            string controllerName = nameof(ScalesController).Substring(0, nameof(ScalesController).Length - "Controller".Length);

            return RedirectToAction(actionName, controllerName);
        }

        [HttpGet]
        public IActionResult AddHIT6Scale()
        {
            ViewData["currentUserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddHIT6Scale(HIT6ScaleAddModel addModel, string currentUserId)
        {
            // Get current user's Id if ModelState is not valid and it's needed to be routed.
            // If not routed on next submission currentUserId is null and ModelState is not valid again.
            ViewData["currentUserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Check if hacker is trying to change userId through page's HTML with other user's Id.
            // Return NotFound if sended user Id is different.
            if (currentUserId != ViewData["currentUserId"]!.ToString())
            {
                return NotFound();
            }

            // Reset custom added model errors for next validation cycle.
            // If reset is skipped even with correct data submission on next user input, ModelState continues to not be valid!
            ModelState[nameof(addModel.FirstQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(addModel.SecondQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(addModel.ThirdQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(addModel.FourthQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(addModel.FifthQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(addModel.SixthQuestionAnswer)]?.Errors.Clear();

            // Check if all Model properties have values.
            // Here default values are evaluated as valid so it's needed custom validation if this one pass.
            if (!ModelState.IsValid)
            {
                return View(addModel);
            }

            // Custom model validation for left questions unanswered and sent with default value
            // or sent with changed radio button's value through page's HTML.
            if (this.HIT6ScaleService.ValidateAnswer(addModel.FirstQuestionAnswer))
            {
                ModelState.AddModelError(nameof(addModel.FirstQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(addModel.SecondQuestionAnswer))
            {
                ModelState.AddModelError(nameof(addModel.SecondQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(addModel.ThirdQuestionAnswer))
            {
                ModelState.AddModelError(nameof(addModel.ThirdQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(addModel.FourthQuestionAnswer))
            {
                ModelState.AddModelError(nameof(addModel.FourthQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(addModel.FifthQuestionAnswer))
            {
                ModelState.AddModelError(nameof(addModel.FifthQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(addModel.SixthQuestionAnswer))
            {
                ModelState.AddModelError(nameof(addModel.SixthQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            // Check again ModelState if custom Model Errors are added.
            if (!ModelState.IsValid)
            {
                return View(addModel);
            }

            try
            {
                await this.HIT6ScaleService.AddAsync(addModel, currentUserId);

                // Get controller's name and action's name without using magic strings.
                string actionName = nameof(ScalesController.MyHIT6Scales);
                string controllerName = nameof(ScalesController).Substring(0, nameof(ScalesController).Length - "Controller".Length);

                return RedirectToAction(actionName, controllerName);
            }
            catch (Exception ex)
            {
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> MyHIT6Scales(int pageIndex = 1, int pageSize = 1, string orderByDate = "NewestFirst")
        {
            // Custom validation against web parameter tampering
            if ((pageSize != 1 &&
                 pageSize != 5 &&
                 pageSize != 10) ||
                (orderByDate != "NewestFirst" &&
                 orderByDate != "OldestFirst"))
            {
                return BadRequest();
            }

            // Get current user's Id.
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["currentUserId"] = currentUserId;

            // Get user's scales.
            PaginatedList<HIT6ScaleViewModel> currentUserScales = await HIT6ScaleService.GetAllAsync(currentUserId, pageIndex, pageSize, orderByDate);

            // Send pagination size and ordering criteria to the view.
            ViewData["pageSize"] = pageSize;
            ViewData["orderByDate"] = orderByDate;

            return View(currentUserScales);
        }

        [HttpGet]
        public async Task<IActionResult> EditHIT6Scale(string id)
        {
            // Get current user's Id.
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["currentUserId"] = currentUserId;

            // Get HIT6 scale
            HIT6ScaleViewModel hit6scaleViewModel = await HIT6ScaleService.GetByIdAsync(id, currentUserId);

            // Check if scale exists and it belongs to the current user.
            if (hit6scaleViewModel == null)
            {
                return NotFound();
            }

            return View(hit6scaleViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditHIT6Scale(HIT6ScaleViewModel viewModel, string userId)
        {
            // Get current user's Id if ModelState is not valid and it's needed to be routed.
            // If not routed on next submission currentUserId is null and ModelState is not valid again.
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["currentUserId"] = currentUserId;

            // Check if hacker is trying to change userId through page's HTML with other user's Id.
            // Return NotFound if sended user Id is different.
            if (userId != currentUserId)
            {
                return NotFound();
            }

            // Reset custom added model errors for next validation cycle.
            // If reset is skipped even with correct data submission on next user input, ModelState continues to not be valid!
            ModelState[nameof(viewModel.FirstQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(viewModel.SecondQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(viewModel.ThirdQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(viewModel.FourthQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(viewModel.FifthQuestionAnswer)]?.Errors.Clear();
            ModelState[nameof(viewModel.SixthQuestionAnswer)]?.Errors.Clear();

            // Check if all Model properties have values.
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            // Custom model validation for changed radio button's value through page's HTML.
            if (this.HIT6ScaleService.ValidateAnswer(viewModel.FirstQuestionAnswer))
            {
                ModelState.AddModelError(nameof(viewModel.FirstQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(viewModel.SecondQuestionAnswer))
            {
                ModelState.AddModelError(nameof(viewModel.SecondQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(viewModel.ThirdQuestionAnswer))
            {
                ModelState.AddModelError(nameof(viewModel.ThirdQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(viewModel.FourthQuestionAnswer))
            {
                ModelState.AddModelError(nameof(viewModel.FourthQuestionAnswer), "Необходимо е да отбележите отговор.");
            }

            if (this.HIT6ScaleService.ValidateAnswer(viewModel.FifthQuestionAnswer))
            {
                ModelState.AddModelError(nameof(viewModel.FifthQuestionAnswer), "Необходимо е да отбележите отговор.");

src/MVCProject.Web/Views/Scales/AddHIT6Scale.cshtml
@model HIT6ScaleAddModel

@{
    ViewData["Title"] = "Добави HIT6 скала";
}


<h1>HIT-6 скала за оценка на главоболие (версия 1.1)</h1>
<section>
    <h3 class="mb-3">
        Моля, отговорете на следните въпроси, като изберете един от възможните отговори.<br />
        Въпросите се отнасят за характеристиката на Вашето главоболие през последните 4 седмици.
    </h3>
</section>
<section>
    <form asp-controller="Scales" asp-action="AddHIT6Scale" asp-route-currentUserId=@ViewData["currentUserId"] method="post">
        <div class="mb-3">
            <label asp-for="FirstQuestionAnswer">
                1. Когато имате главоболие, колко често болката е много силна?
            </label> <br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="NoAnswer" checked="checked" style="display: none;" />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="FirstQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SecondQuestionAnswer">
                2. Колко често главоболията са ограничавали Вашите обичайни дейности, напр.<br />
                домакинска работа, професионална работа, учебна дейност, социални активности?
            </label> <br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="NoAnswer" checked="checked" style="display: none;" />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="SecondQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ThirdQuestionAnswer">
                3. Когато имате главоболие, колко често Ви се е приисквало да полегнете?
            </label> <br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="NoAnswer" checked="checked" style="display: none;" />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="ThirdQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FourthQuestionAnswer">
                4. Колко често сте се чувствали твърде изморени за извършване на Вашите<br />
                професионални и всекидневни задължения заради Вашите главоболия?
            </label> <br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="NoAnswer" checked="checked" style="display: none;" />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="FourthQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FifthQuestionAnswer">
                5. Колко често Ви е идвало до гуша или сте се чувствали раздразнени поради Вашите главоболия?
            </label> <br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="NoAnswer" checked="checked" style="display: none;" />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="FifthQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SixthQuestionAnswer">
                6. Колко често главоболията са пречили на концентрацията Ви?
            </label> <br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="NoAnswer" checked="checked" style="display: none;" />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="SixthQuestionAnswer" class="text-danger"></span>
        </div>

        <input type="submit" class="btn btn-primary" value="Добави" />
    </form>
</section>

src/MVCProject.Web/Views/Scales/EditHIT6Scale.cshtml
@model HIT6ScaleViewModel

@{
    ViewData["Title"] = "Редактирай HIT-6 скала";
}

<h1 class="text-center">Редактиране на HIT-6 скала.</h1>
<section>
    <form asp-controller="Scales" asp-action="EditHIT6Scale" asp-route-userId=@ViewData["currentUserId"] method="post">
        <div class="mb-3">
            <label asp-for="FirstQuestionAnswer">
                1. Когато имате главоболие, колко често болката е много силна?
            </label> <br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="FirstQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="FirstQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SecondQuestionAnswer">
                2. Колко често главоболията са ограничавали Вашите обичайни дейности, напр.<br />
                домакинска работа, професионална работа, учебна дейност, социални активности?
            </label> <br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="SecondQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="SecondQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ThirdQuestionAnswer">
                3. Когато имате главоболие, колко често Ви се е приисквало да полегнете?
            </label> <br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="ThirdQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="ThirdQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FourthQuestionAnswer">
                4. Колко често сте се чувствали твърде изморени за извършване на Вашите<br />
                професионални и всекидневни задължения заради Вашите главоболия?
            </label> <br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="FourthQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="FourthQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FifthQuestionAnswer">
                5. Колко често Ви е идвало до гуша или сте се чувствали раздразнени поради Вашите главоболия?
            </label> <br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="FifthQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="FifthQuestionAnswer" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SixthQuestionAnswer">
                6. Колко често главоболията са пречили на концентрацията Ви?
            </label> <br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Never" /> Никога<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Rarely" /> Рядко<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Sometimes" /> Понякога<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Very often" /> Много често<br />
            <input type="radio" asp-for="SixthQuestionAnswer" value="Always" /> Винаги<br />
            <span asp-validation-for="SixthQuestionAnswer" class="text-danger"></span>
        </div>

        <input type="submit" class="btn btn-primary" value="Запази" onclick="confirmEdit(event);" />
    </form>
</section>
<script src="~/js/confirmEdit.js"></script>

src/MVCProject.Web/Views/Scales/MyHIT6Scales.cshtml
@model PaginatedList<HIT6ScaleViewModel>

@{
    ViewData["Title"] = "Моите HIT-6 скали";
    ViewData["PartialViewController"] = "Scales";
    ViewData["PartialViewAction"] = "MyHIT6Scales";
    ViewData["itemsType"] = "Скали";
    ViewData["entityCounter"] = 1;

    int scaleCounter = 1;
}

@if (Model.Count == 0)
{
    <section>
        <p>Изглежда все още нямате регистрирани HIT-6 скали за самооценка. Защо не регистрирате първата си скала от <a asp-controller="Scales" asp-action="AddHIT6Scale">тук</a>?</p>
    </section>
}
else
{
    <section>
        <h3 class="text-center">Регистрирани HIT-6 скали</h3>
        <partial name="_PageItemsOrderingNavigation" view-data="ViewData" />
        <div class="container mt-4">
            <div class="row">
                @foreach (var scale in Model)
                {
                    <h4 class="text-center article-title">HIT-6 скала № @(scaleCounter * Model.CurrentPageIndex)</h4>
                    <input type="hidden" id="entityID-@scaleCounter" entitytype="HIT6scale" value="@scale.Id">
                    <p class="text-center mb-5">Дата на добавяне: @scale.CreatedOn.ToShortDateString()</p>
                    <p><i>1. Когато имате главоболие, колко често болката е много силна?</i></p>
                    @if (scale.FirstQuestionAnswer == "Never")
                    {
                        <p>Отговор: никога.</p>
                    }
                    else if (scale.FirstQuestionAnswer == "Rarely")
                    {
                        <p>Отговор: рядко.</p>
                    }
                    else if (scale.FirstQuestionAnswer == "Sometimes")
                    {
                        <p>Отговор: понякога.</p>
                    }
                    else if (scale.FirstQuestionAnswer == "Very often")
                    {
                        <p>Отговор: много често.</p>
                    }
                    else if (scale.FirstQuestionAnswer == "Always")
                    {
                        <p>Отговор: винаги.</p>
                    }

                    <p>
                        <i>
                            2. Колко често главоболията са ограничавали Вашите обичайни дейности, напр.<br />
                            домакинска работа, професионална работа, учебна дейност, социални активности?
                        </i>
                    </p>
                    @if (scale.SecondQuestionAnswer == "Never")
                    {
                        <p>Отговор: никога.</p>
                    }
                    else if (scale.SecondQuestionAnswer == "Rarely")
                    {
                        <p>Отговор: рядко.</p>
                    }
                    else if (scale.SecondQuestionAnswer == "Sometimes")
                    {
                        <p>Отговор: понякога.</p>
                    }
                    else if (scale.SecondQuestionAnswer == "Very often")
                    {
                        <p>Отговор: много често.</p>
                    }
                    else if (scale.SecondQuestionAnswer == "Always")
                    {
                        <p>Отговор: винаги.</p>
                    }

                    <p><i>3. Когато имате главоболие, колко често Ви се е приисквало да полегнете?</i></p>
                    @if (scale.ThirdQuestionAnswer == "Never")
                    {
                        <p>Отговор: никога.</p>
                    }
                    else if (scale.ThirdQuestionAnswer == "Rarely")
                    {
                        <p>Отговор: рядко.</p>
                    }
                    else if (scale.ThirdQuestionAnswer == "Sometimes")
                    {
                        <p>Отговор: понякога.</p>
                    }
                    else if (scale.ThirdQuestionAnswer == "Very often")
                    {
                        <p>Отговор: много често.</p>
                    }
                    else if (scale.ThirdQuestionAnswer == "Always")
                    {
                        <p>Отговор: винаги.</p>
                    }

                    <p>
                        <i>
                            4. Колко често сте се чувствали твърде изморени за извършване на Вашите<br />
                            професионални и всекидневни задължения заради Вашите главоболия?
                        </i>
                    </p>
                    @if (scale.FourthQuestionAnswer == "Never")
                    {
                        <p>Отговор: никога.</p>
                    }
                    else if (scale.FourthQuestionAnswer == "Rarely")
                    {
                        <p>Отговор: рядко.</p>
                    }
                    else if (scale.FourthQuestionAnswer == "Sometimes")
                    {
                        <p>Отговор: понякога.</p>
                    }
                    else if (scale.FourthQuestionAnswer == "Very often")
                    {
                        <p>Отговор: много често.</p>
                    }
                    else if (scale.FourthQuestionAnswer == "Always")
                    {
                        <p>Отговор: винаги.</p>
                    }

                    <p><i>5. Колко често Ви е идвало до гуша или сте се чувствали раздразнени поради Вашите главоболия?</i></p>
                    @if (scale.FifthQuestionAnswer == "Never")
                    {
                        <p>Отговор: никога.</p>
                    }
                    else if (scale.FifthQuestionAnswer == "Rarely")
                    {
                        <p>Отговор: рядко.</p>
                    }
                    else if (scale.FifthQuestionAnswer == "Sometimes")
                    {
                        <p>Отговор: понякога.</p>
                    }
                    else if (scale.FifthQuestionAnswer == "Very often")
                    {
                        <p>Отговор: много често.</p>
                    }
                    else if (scale.FifthQuestionAnswer == "Always")
                    {
                        <p>Отговор: винаги.</p>
                    }

                    <p><i>6. Колко често главоболията са пречили на концентрацията Ви?</i></p>
                    @if (scale.SixthQuestionAnswer == "Never")
                    {
                        <p>Отговор: никога.</p>
                    }
                    else if (scale.SixthQuestionAnswer == "Rarely")
                    {
                        <p>Отговор: рядко.</p>
                    }
                    else if (scale.SixthQuestionAnswer == "Sometimes")
                    {
                        <p>Отговор: понякога.</p>
                    }
                    else if (scale.SixthQuestionAnswer == "Very often")
                    {
                        <p>Отговор: много често.</p>
                    }
                    else if (scale.SixthQuestionAnswer == "Always")
                    {
                        <p>Отговор: винаги.</p>
                    }

                    <p><b>Резултат: <a href="#" title="Разбери как да тълкуваш резултата като кликнеш тук.">@scale.TotalScore</a> точки.</b></p>

                    <partial name="_SearchAndSharePartial" model="@scale.Doctors" view-data="ViewData" />

                    <div class="edit-delete-container">
                        <div class="mb-3">
                            <a asp-controller="Scales" asp-action="EditHIT6Scale" asp-route-id="@scale.Id" class="btn btn-warning border-dark">Редактирай</a>

                            <a asp-controller="Scales" asp-action="DeleteHIT6Scale" asp-route-hit6scaleId="@scale.Id" asp-route-currentUserId=@ViewData["currentUserId"] class="btn btn-danger border-dark" style="position:relative; right: -30px;" onclick="confirmDelete(event, @scaleCounter);">Изтрий</a>
                        </div>
                    </div>

                    <hr />
                    scaleCounter++;
                    ViewData["entityCounter"] = scaleCounter;
                }
            </div>
        </div>
    </section>
    <partial name="_PagesNavigation" view-data="ViewData" />
}
<script src="~/js/confirmDelete.js"></script>
<script src="~/js/search.js"></script>
<script src="~/js/shareHIT6scale.js"></script>